[project]
name = "ms-cluster-formula-search"
version = "0.1.0"
description = "Mass spectrometry formula enumeration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
]

[project.scripts]
search-formula = "formula_search:main"
